service: local-chat-server
frameworkVersion: '2'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: us-west-2
  environment: ${file(config/env.yml):variables}

functions:
  hello:
    handler: src/dev.hello
  createUser:
    handler: src/users.create
    events:
      - http:
          method: POST
          path: /users/create
  createChat:
    handler: src/chats.create
    events:
      - http:
          method: POST
          path: /chats/create
  sendMessage:
    handler: src/messages.send
    events:
      - http:
          method: POST
          path: /messages/send
