service: local-chat-server
frameworkVersion: '2'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: us-west-2
  environment: ${file(config/env.yml):variables}

functions:
  hello:
    handler: src/dev.hello
